steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
  # Install dependencies
  - name: python
    entrypoint: python
    args: ["lark_test.py"]
