steps:
- name: 'gcr.io/$PROJECT_ID/p2p-cloudbuild' 
  entrypoint: '/bin/bash'
  args:
    - '-c'
    - |
      virtualenv /workspace/venv
      source /workspace/venv/bin/activate
      pip install -V -r requirements.txt
      python -c 'from main import foo; print (foo())'
