steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  args:
  - "-c"
  - |
    echo "Docker Container Built"
    sudo apt update
    sudo apt install python3 python3-dev python3-venv
    wget https://bootstrap.pypa.io/get-pip.py
    sudo python3 get-pip.py
    pip --version
    pip install lark --upgrade/
